### ISSUE TITLE
Fail to connect to localhost port

### ISSUE THREAD

**Issue by yuhang199** [comp426-2022-spring/a01-yuhang199#2]
I have everything coded in the video, but all the errors occurred when autograder tris test port other than 3000. How can I fix that?

**Comment by camsimba** [comment]
Hey,

It looks like you might have an issue with the 'minimist' dependency. Other students have had issues with this same problem, and a solution one of them had was to rerun the command `npm install minimist` and then resubmit. Let me know if this helped any. Also, you should add `node_modules` to your .gitignore file like stated in the write-up.

As a side note, if you have issues with future assignments it'd be more expedient to create a new issue under the shared assignment repository rather than your personal one, as we can see those much easier than each students individual repository. Doing it this way is still fine, but it may take longer to get help.

Let me know if you still need help or have any questions and I'll help in whatever way I can!

**Comment by yuhang199** [comment]
thank you!
